### ISSUE TITLE
IQM support?

### ISSUE THREAD

**Issue by mgerhardy** [PadWorld-Entertainment/wop-mapeditor-support#2]
https://github.com/PadWorld-Entertainment/wop-mapeditor-support/blob/271759c575407d3a48659b98d444183fdc63ec45/netradiant/games/wop.game#L21

not sure if we want to add this here.

**Comment by kai-li-wop** [comment]
Thanks for the hint! Updated with 3276b9d4c330fc2c03491f276bb2aa7524b6b385
